import type { TourismData } from "./types"

export const tourismData: TourismData = {
  attractions: [
    {
      id: "burnham-park",
      name: "Burnham Park",
      district: "Central Business District",
      location: "Jose Abad Santos Drive",
      openingHours: "Open daily, best before 9:00 AM",
      tags: ["parks", "family", "walkable", "budget"],
      baselineCrowd: "high",
      carFreeHint: "Walk from Session Road or use taxis only for drop-off outside peak hours.",
      wasteReminder: "Use refillable bottles and avoid disposable picnic packaging.",
      durationHours: 2,
    },
    {
      id: "botanical-garden",
      name: "Baguio Botanical Garden",
      district: "Leonard Wood",
      location: "37 Leonard Wood Road",
      openingHours: "6:00 AM - 6:00 PM",
      tags: ["nature", "culture", "photography"],
      baselineCrowd: "moderate",
      carFreeHint: "Pair with Wright Park and walk between nearby stops.",
      wasteReminder: "Keep food waste sealed and use designated bins only.",
      durationHours: 2,
    },
    {
      id: "mines-view",
      name: "Mines View Park",
      district: "Outlook Drive",
      location: "Mines View Observation Deck",
      openingHours: "Open daily, morning recommended",
      tags: ["viewpoint", "souvenirs", "high-traffic"],
      baselineCrowd: "critical",
      carFreeHint: "Avoid driving to the viewpoint; use public transport and visit early.",
      wasteReminder: "Refuse single-use bags when buying souvenirs.",
      durationHours: 1.5,
    },
    {
      id: "ben-cab",
      name: "BenCab Museum",
      district: "Tuba boundary",
      location: "Km. 6 Asin Road",
      openingHours: "9:00 AM - 6:00 PM, closed Mondays",
      tags: ["art", "museum", "paid"],
      baselineCrowd: "moderate",
      carFreeHint: "Book shared transport or taxi pooling because Asin Road is outside the walkable core.",
      wasteReminder: "Carry out snack wrappers and avoid disposable cafe items.",
      durationHours: 2.5,
    },
    {
      id: "session-road",
      name: "Session Road",
      district: "Central Business District",
      location: "Session Road",
      openingHours: "Open daily",
      tags: ["food", "shopping", "walkable", "night"],
      baselineCrowd: "high",
      carFreeHint: "Leave the car parked; Session Road is best handled on foot.",
      wasteReminder: "Choose dine-in where possible and bring a small reusable bag.",
      durationHours: 2,
    },
    {
      id: "camp-john-hay",
      name: "Camp John Hay Historical Core",
      district: "Loakan",
      location: "Camp John Hay",
      openingHours: "Open daily, hours vary by establishment",
      tags: ["heritage", "forest", "walking"],
      baselineCrowd: "moderate",
      carFreeHint: "Use a single drop-off and walk inside the estate to reduce short car hops.",
      wasteReminder: "Bring back all trail litter and avoid disposable coffee cups.",
      durationHours: 3,
    },
  ],
  events: [
    {
      id: "panagbenga",
      name: "Panagbenga Festival Window",
      startsOn: "2026-02-01",
      endsOn: "2026-03-08",
      impact: "critical",
      notes: "Festival season usually raises road closures, crowding, and accommodation pressure.",
    },
    {
      id: "sample-long-weekend",
      name: "Sample Long Weekend Surge",
      startsOn: "2026-08-21",
      endsOn: "2026-08-24",
      impact: "high",
      notes: "Use as an admin-editable rule for holiday or long-weekend demand.",
    },
  ],
  advisories: [
    {
      id: "leave-car-cbd",
      title: "Avoid private cars in the CBD",
      severity: "warning",
      area: "Burnham Park, Session Road, public market",
      message: "Use walking links, taxis, or jeepney routes for central stops during peak periods.",
    },
    {
      id: "bring-reusables",
      title: "Bring reusables",
      severity: "info",
      area: "Citywide",
      message: "Carry a tumbler, reusable utensils, and a small trash pouch for low-waste touring.",
    },
    {
      id: "capacity-sensitive",
      title: "Capacity-sensitive planning",
      severity: "urgent",
      area: "High-traffic attractions",
      message: "Shift popular stops to early mornings and avoid stacking congested attractions on the same day.",
    },
  ],
  crowdRules: [
    {
      id: "weekday",
      label: "Weekday baseline",
      condition: "Monday to Thursday",
      scoreImpact: 10,
    },
    {
      id: "weekend",
      label: "Weekend visitor surge",
      condition: "Friday to Sunday",
      scoreImpact: 28,
    },
    {
      id: "festival",
      label: "Festival or major event",
      condition: "Date overlaps a configured event",
      scoreImpact: 32,
    },
    {
      id: "private-car",
      label: "Private car pressure",
      condition: "Planner includes private car use",
      scoreImpact: 12,
    },
  ],
}

export const ecoReminders = [
  "Bring a tumbler and refill before leaving the hotel.",
  "Avoid single-use plastics for snacks, coffee, and souvenirs.",
  "Dispose waste only in designated bins; carry a small trash pouch between stops.",
  "Prefer walkable clusters and shared rides over short private-car hops.",
]
